Added -Wl,--no-as-needed to LDFLAGS to fix Bug #203150: x11-wm/matchbox-0.7.1: undefined reference to XShm* w/ --as-needed Package-Manager: portage-2.1.4.1